### ISSUE TITLE
PackagesNotFoundError: The following packages are not available from current channels: - rdf_data_citation

### ISSUE THREAD

**Issue by allNormal** [GreenfishK/DataCitation#1]
Hi, im getting this error when trying to create a new conda env using the rdf_data_citation package on windows.
---
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

* rdf_data_citation=0.9.7.5

Current channels:

* [https://repo.anaconda.com/pkgs/main/win-64](https://repo.anaconda.com/pkgs/main/win-64)
* [https://repo.anaconda.com/pkgs/main/noarch](https://repo.anaconda.com/pkgs/main/noarch)
* [https://repo.anaconda.com/pkgs/free/win-64](https://repo.anaconda.com/pkgs/free/win-64)
* [https://repo.anaconda.com/pkgs/free/noarch](https://repo.anaconda.com/pkgs/free/noarch)
* [https://repo.anaconda.com/pkgs/r/win-64](https://repo.anaconda.com/pkgs/r/win-64)
* [https://repo.anaconda.com/pkgs/r/noarch](https://repo.anaconda.com/pkgs/r/noarch)
* [https://repo.anaconda.com/pkgs/msys2/win-64](https://repo.anaconda.com/pkgs/msys2/win-64)
* [https://repo.anaconda.com/pkgs/msys2/noarch](https://repo.anaconda.com/pkgs/msys2/noarch)

To search for alternate channels that may provide the conda package you're
looking for, navigate to

[https://anaconda.org](https://anaconda.org)

and use the search bar at the top of the page.

---

already try to install it using "conda install -c conda-forge", but it doesn't change anything.

**Comment by GreenfishK** [comment]
Hi, did you try the command "conda install -c greenfish rdf_data_citation" ?
Please try to create a conda environment, then switch to it using the terminal with "conda activate yourenvname"  and then issue the install command.

**Comment by allNormal** [comment]
Hi, It works now, installing inside the environment + solving some path issues solves the problem for me, but can confirm that the command "conda install -c greenfish rdf_data_citation" doesn't work on windows, so manually install the package is the way to go.

**Comment by GreenfishK** [comment]
> Hi, It works now, installing inside the environment + solving some path issues solves the problem for me, but can confirm that the command "conda install -c greenfish rdf_data_citation" doesn't work on windows, so manually install the package is the way to go.

Thank's for checking! Yes, I guessed that for windows it might not worked because I focused only on Linux in the first instance. Nevertheless, I am keeping this in the backlog and in near future the installation should also work for windows.
